<a href="https://colab.research.google.com/github/kyungmo90/Ubion-Python/blob/main/20230102%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%A7%88%EC%BC%80%ED%8C%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#2023.01.02
#빅데이터 마케팅 과정
#권혁준

In [ ]:
a = 123
b = "abc"
print(type(a), type(b))
print(a, b)

<class 'int'> <class 'str'>
123 abc


In [ ]:
List = ["a", "b", "c", "d"] 
List

['a', 'b', 'c', 'd']

In [ ]:
Tuple = ("a", "b", "c", "d")
Tuple

('a', 'b', 'c', 'd')

In [ ]:
Dic = {"경기도" : "김포", "강원도" : "원주", "충청도" : "청주"}
Dic

{'경기도': '김포', '강원도': '원주', '충청도': '청주'}

In [ ]:
score = 60
if score > 40 :
    print("vip")
else :
    print("member")

vip


In [ ]:
for i in [1,2,3,4,5] :
   print(i)

1
2
3
4
5


In [ ]:
for i in range(10):
   print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
customer_count = 0
sum1 = 0

print("customer_count_sum")

while (sum1 < 20) :
    customer_count = customer_count + 1
    sum1 = sum1 + customer_count
    print(customer_count, sum1)

customer_count_sum
1 1
2 3
3 6
4 10
5 15
6 21


In [ ]:
from matplotlib import pyplot as plt
from pandas import DataFrame
import numpy as np
from pandas import *

In [ ]:
data = [1,2,3,4,5,6]
arr1 = np.array(data)
arr1

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr1 = np.arange(start = 1, stop = 20, step = 2)
print(arr1)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
arr2 = np.arange(10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr1 = np.array([10,12,14,16,18])
arr2 = np.array([3,4,5,6,7])

print("----더하기----")
print(arr1+arr2)
print("----빼기----")
print(arr1-arr2)
print("----곱하기----")
print(arr1*arr2)
print("----나누기----")
print(arr1/arr2)

----더하기----
[13 16 19 22 25]
----빼기----
[ 7  8  9 10 11]
----곱하기----
[ 30  48  70  96 126]
----나누기----
[3.33333333 3.         2.8        2.66666667 2.57142857]


In [ ]:
arr1[4] = 20
print(arr1)

[10 12 14 16 20]


In [ ]:
arr1[1,3,4]

IndexError: ignored

In [ ]:
arr3 = np.array([1,3,5,7,9,11])
arr3

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
arr3[1:5]

array([3, 5, 7, 9])

In [ ]:
arr4 = np.arange(10)
arr4 = arr4.reshape(2,5,1)
arr4

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [ ]:
arr5 = np.arange(20)
arr5 = arr5.reshape(-1, 5)
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
import pandas as pd

In [ ]:
series = pd.Series([1,2,3,4,5])
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
pd.DataFrame(series)

0
0  1
1  2
2  3
3  4
4  5

In [ ]:
col_list = ["name", "age", "grade"]
val_list = [["유한별", 34, "silver"], ["강동원", 40, "diamond"], ["옥동자", 45, "gold"]]
pd.DataFrame(data = val_list, columns = col_list)

name  age    grade
0  유한별   34   silver
1  강동원   40  diamond
2  옥동자   45     gold

In [ ]:
dict = {"고객이름" : ["권혁준", "강동원", "옥동자"], "나이" : [25,40,45], "등급" : ["silver", "diamond", "gold"]}
pd.DataFrame(data = dict)

고객이름  나이       등급
0  권혁준  25   silver
1  강동원  40  diamond
2  옥동자  45     gold

In [ ]:
sales_data = {"화장품" : [300, 250, 150, 524, 211],
              "의류" : [170, 182, 193, 324, 487],
              "식품" : [220, 231, 452, 520, 152],
              "전자제품" : [500, 345, 152, 540, 290]}
col_list = ["화장품", "의류", "식품", "전자제품"]
index_list = ["2017", "2018", "2019", "2020", "2021"]

df_sales = pd.DataFrame(data = sales_data, columns = col_list, index = index_list)
df_sales

화장품   의류   식품  전자제품
2017  300  170  220   500
2018  250  182  231   345
2019  150  193  452   152
2020  524  324  520   540
2021  211  487  152   290

In [ ]:
print(df_sales.mean())

화장품     287.0
의류      271.2
식품      315.0
전자제품    365.4
dtype: float64


In [ ]:
print(df_sales.std())

화장품     143.398047
의류      135.711827
식품      160.813557
전자제품    158.306033
dtype: float64


In [ ]:
df_sales.describe()

화장품          의류          식품        전자제품
count    5.000000    5.000000    5.000000    5.000000
mean   287.000000  271.200000  315.000000  365.400000
std    143.398047  135.711827  160.813557  158.306033
min    150.000000  170.000000  152.000000  152.000000
25%    211.000000  182.000000  220.000000  290.000000
50%    250.000000  193.000000  231.000000  345.000000
75%    300.000000  324.000000  452.000000  500.000000
max    524.000000  487.000000  520.000000  540.000000

In [ ]:
sales_data2 = {"화장품" : [300, 250, 150, 524, 211, 267, 192],
              "의류" : [170, 182, 193, 324, 487, 502, 810],
              "식품" : [220, 231, 452, 520, 152, np.nan, np.nan],
              "전자제품" : [500, 345, 152, 540, 290, 125, 318]}
col_list = ["화장품", "의류", "식품", "전자제품"]
index_list = ["2017", "2018", "2019", "2020", "2021", "2022", "2023"]

df_sales2 = pd.DataFrame(data = sales_data2, columns = col_list, index = index_list)
df_sales2

화장품   의류     식품  전자제품
2017  300  170  220.0   500
2018  250  182  231.0   345
2019  150  193  452.0   152
2020  524  324  520.0   540
2021  211  487  152.0   290
2022  267  502    NaN   125
2023  192  810    NaN   318

In [ ]:
df_sales2.loc["2022"]

화장품     267.0
의류      502.0
식품        NaN
전자제품    125.0
Name: 2022, dtype: float64

In [ ]:
df_sales2["식품"]["2022":"2023"]

2022   NaN
2023   NaN
Name: 식품, dtype: float64

In [ ]:
df_sales2.loc["2022", "식품"]

nan

In [ ]:
df_sales2.iloc[2:4, 0]

2019    150
2020    524
Name: 화장품, dtype: int64

In [ ]:
df_sales2.columns

Index(['화장품', '의류', '식품', '전자제품'], dtype='object')

In [ ]:
df_sales2.isnull().sum()

화장품     0
의류      0
식품      2
전자제품    0
dtype: int64

In [ ]:
df_sales2_row = df_sales2.dropna(axis=0)
df_sales2_row

화장품   의류     식품  전자제품
2017  300  170  220.0   500
2018  250  182  231.0   345
2019  150  193  452.0   152
2020  524  324  520.0   540
2021  211  487  152.0   290

In [ ]:
df_sales2_col = df_sales2.dropna(axis=1)
df_sales2_col

화장품   의류  전자제품
2017  300  170   500
2018  250  182   345
2019  150  193   152
2020  524  324   540
2021  211  487   290
2022  267  502   125
2023  192  810   318

In [ ]:
df_sales2_zero = df_sales2.fillna(0)
df_sales2_zero

화장품   의류     식품  전자제품
2017  300  170  220.0   500
2018  250  182  231.0   345
2019  150  193  452.0   152
2020  524  324  520.0   540
2021  211  487  152.0   290
2022  267  502    0.0   125
2023  192  810    0.0   318

In [ ]:
df_sales2_mean = df_sales2.fillna(df_sales2["식품"].mean())
df_sales2_mean

화장품   의류     식품  전자제품
2017  300  170  220.0   500
2018  250  182  231.0   345
2019  150  193  452.0   152
2020  524  324  520.0   540
2021  211  487  152.0   290
2022  267  502  315.0   125
2023  192  810  315.0   318