<a href="https://colab.research.google.com/github/kyungmo90/Ubion-Python/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%A7%88%EC%BC%80%ED%8C%85_%EB%B6%84%EC%84%9D_%EC%A0%84%EB%AC%B8%EA%B0%80_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

빅데이터 마케팅 분석 전문가 #2

박경모

2023.01.02.

In [ ]:
a = 123
b = 'abc'
print(type(a), type(b))
print(a, b)

<class 'int'> <class 'str'>
123 abc


In [ ]:
List = ["a", "b", "c", "d"]

In [ ]:
List

['a', 'b', 'c', 'd']

In [ ]:
Tuple = ("a","b","c","d")
Tuple

('a', 'b', 'c', 'd')

In [ ]:
Dic = {"경기도" : "김포", "강원도" : "원주", "충청도" : "청주"}

In [ ]:
Dic

{'경기도': '김포', '강원도': '원주', '충청도': '청주'}

In [ ]:
score = 20
if score > 40 :
    print("vip")
else :
  print("member")

member


In [ ]:
for i in [1,2,3,4,5] :
     print(i)

1
2
3
4
5


In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
customer_count = 0
sum1 = 0

print("customer_count_sum")

while (sum1 < 20) :
    customer_count = customer_count + 1
    sum1 = sum1 + customer_count
    print(customer_count, sum1)

customer_count_sum
1 1
2 3
3 6
4 10
5 15
6 21


Numpy

In [ ]:
from matplotlib import pyplot as pyplot
from pandas import DataFrame
import numpy as np
from pandas import *

In [ ]:
data = {1,2,3,4,5,6}
arr1 = np.array(data)
arr1

array({1, 2, 3, 4, 5, 6}, dtype=object)

In [ ]:
arr1.dtype

dtype('O')

In [ ]:
arr1 = np.arange(start = 1, stop = 20, step = 2)
print(arr1)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
arr1 = np.array([10,12,14,16,18])
arr2 = np.array([3,4,5,6,7])

print("----더하기----")
print(arr1+arr2)
print("----빼기----")
print(arr1-arr2)
print("----곱하기----")
print(arr1*arr2)
print("----나누기----")
print(arr1/arr2)

----더하기----
[13 16 19 22 25]
----빼기----
[ 7  8  9 10 11]
----곱하기----
[ 30  48  70  96 126]
----나누기----
[3.33333333 3.         2.8        2.66666667 2.57142857]


In [ ]:
arr1[4] = 20
print(arr1)

[10 12 14 16 20]


In [ ]:
arr1[1,3,4]

IndexError: ignored

In [ ]:
arr3 = np.array([1,3,5,7,9,11])
arr3

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
arr3[1:5]

array([3, 5, 7, 9])

In [ ]:
arr4 = np.arange(10)
arr4 = arr4.reshape(2,5,1)
arr4

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [ ]:
arr5 = np.arange(20)
arr5 = arr5.reshape(-1,5)
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#pandas

In [ ]:
import pandas as pd

In [ ]:
series = pd.Series([1,2,3,4,5])
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
pd.DataFrame(series)

0
0  1
1  2
2  3
3  4
4  5

In [ ]:
col_list = ["고객이름", "나이", "등급"]
val_list = [["박경모", 32, "silver"], ["원빈", 40, "gold"], ["옥동자", 45, "diamond"]]
pd.DataFrame(data = val_list, columns = col_list)

고객이름  나이       등급
0  박경모  32   silver
1   원빈  40     gold
2  옥동자  45  diamond

In [ ]:
dict = {"고객이름" : ["박경모", "강동원", "옥동자"], "나이" : [34,40,45], "등급" : ["silver","diamond","gold"]}
pd.DataFrame(data = dict)

고객이름  나이       등급
0  박경모  34   silver
1  강동원  40  diamond
2  옥동자  45     gold

In [ ]:
sales_data2 = {"화장품" : [300, 250, 150, 524, 211, 267, 192],
              "의류" : [170, 182, 193, 324, 487, 502, 810],
              "식품" : [220, 2310, 452, 520, 152, np.nan, np.nan],
              "전자제품" : [500, 345, 152, 540, 290, 125, 318]}
col_list = ["화장품", "의류", "식품", "전자제품"]
index_list = ["2017", "2018", "2019", "2020", "2021", "2022", "2023"]

df_sales2 = pd.DataFrame(data = sales_data2, columns = col_list, index = index_list)
df_sales2

화장품   의류      식품  전자제품
2017  300  170   220.0   500
2018  250  182  2310.0   345
2019  150  193   452.0   152
2020  524  324   520.0   540
2021  211  487   152.0   290
2022  267  502     NaN   125
2023  192  810     NaN   318

In [ ]:
print(df_sales.mean())

화장품     287.0
의류      271.2
식품      730.8
전자제품    365.4
dtype: float64


In [ ]:
print(df_sales.std())

화장품     143.398047
의류      135.711827
식품      896.097763
전자제품    158.306033
dtype: float64


In [ ]:
df_sales.describe()

화장품          의류           식품        전자제품
count    5.000000    5.000000     5.000000    5.000000
mean   287.000000  271.200000   730.800000  365.400000
std    143.398047  135.711827   896.097763  158.306033
min    150.000000  170.000000   152.000000  152.000000
25%    211.000000  182.000000   220.000000  290.000000
50%    250.000000  193.000000   452.000000  345.000000
75%    300.000000  324.000000   520.000000  500.000000
max    524.000000  487.000000  2310.000000  540.000000

In [ ]:
df_sales2.loc["2022"]

화장품     267.0
의류      502.0
식품        NaN
전자제품    125.0
Name: 2022, dtype: float64

In [ ]:
df_sales2["식품"]["2022":"2023"]

2022   NaN
2023   NaN
Name: 식품, dtype: float64

In [ ]:
df_sales2.loc["2022","식품"]

nan

In [ ]:
df_sales2.iloc[2:4,0]

2019    150
2020    524
Name: 화장품, dtype: int64

In [ ]:
df_sales2.columns

Index(['화장품', '의류', '식품', '전자제품'], dtype='object')

In [ ]:
df_sales2.isnull().sum()

화장품     0
의류      0
식품      2
전자제품    0
dtype: int64

In [ ]:
df_sales2_row = df_sales2.dropna(axis=0)
df_sales2_row

화장품   의류      식품  전자제품
2017  300  170   220.0   500
2018  250  182  2310.0   345
2019  150  193   452.0   152
2020  524  324   520.0   540
2021  211  487   152.0   290

In [ ]:
df_sales2_col = df_sales2.dropna(axis=1)
df_sales2_col

화장품   의류  전자제품
2017  300  170   500
2018  250  182   345
2019  150  193   152
2020  524  324   540
2021  211  487   290
2022  267  502   125
2023  192  810   318

In [ ]:
df_sales2_zero = df_sales2.fillna(0)
df_sales2_zero

화장품   의류      식품  전자제품
2017  300  170   220.0   500
2018  250  182  2310.0   345
2019  150  193   452.0   152
2020  524  324   520.0   540
2021  211  487   152.0   290
2022  267  502     0.0   125
2023  192  810     0.0   318

In [ ]:
df_sales2_mean = df_sales2.fillna(df_sales2["식품"].mean())
df_sales2_mean

화장품   의류      식품  전자제품
2017  300  170   220.0   500
2018  250  182  2310.0   345
2019  150  193   452.0   152
2020  524  324   520.0   540
2021  211  487   152.0   290
2022  267  502   730.8   125
2023  192  810   730.8   318

In [3]:
import pandas as pd

In [9]:
df = pd.read_csv("/content/drive/MyDrive/Ashopping.csv", encoding= "cp949") #encoding = "utf-8"

In [10]:
df

고객ID  이탈여부      총매출액  구매금액대  방문빈도  1회 평균매출액  할인권 사용 횟수  총 할인 금액  고객등급  \
0       1     1   4963160      1    22    225598          1     5445     1   
1       2     1   2271520      0    38     59777         22   350995     1   
2       3     1   2484250      0     2   1242125          6   186045     1   
3       4     1   2778850      0     9    308761          1     5195     2   
4       5     1   4437610      1    10    443761          9   246350     2   
..    ...   ...       ...    ...   ...       ...        ...      ...   ...   
995   996     0  12731560      2    35    363759          3    44445     2   
996   997     0   3419010      0     6    569835          6   186545     1   
997   998     0   4612100      1    13    354777          8   260700     2   
998   999     0   5165360      1    28    184477         20   347700     1   
999  1000     0   4323050      1    16    270191         19   367045     2   

     구매유형  ...  구매카테고리수  거주지역  성별  고객 나이대  거래기간  할인민감여부  Recency  Frequency  \
0       3  ...        7     6   1       6  3303       0        3          2   
1       1  ...        5     4   0       2  3129       0        5          3   
2       2  ...        4     6   0       3  3636       0        4          1   
3       4  ...        4     5   0       4  3637       0        7          4   
4       4  ...        6     6   0       4  3638       0        5          1   
..    ...  ...      ...   ...  ..     ...   ...     ...      ...        ...   
995     3  ...        8     6   0       4  4629       1        3          3   
996     2  ...        9     6   0       4  4630       1        7          3   
997     1  ...        1     4   1       6  4631       1        2          1   
998     3  ...        7     5   1       6  3907       0        7          2   
999     4  ...        6     5   1       6  2118       0        5          1   

     Monetary      평균 구매주기  
0           1   149.136364  
1           4    81.342105  
2           4  1817.000000  
3           6   403.111111  
4           4   362.800000  
..        ...          ...  
995         1   131.257143  
996         6   770.666667  
997         2   355.230769  
998         6   138.535714  
999         4   131.375000  

[1000 rows x 21 columns]

In [12]:
df.describe()

고객ID         이탈여부          총매출액        구매금액대        방문빈도  \
count  1000.000000  1000.000000  1.000000e+03  1000.000000  1000.00000   
mean    500.500000     0.300000  5.858013e+06     0.700000    22.91100   
std     288.819436     0.458487  5.812815e+06     0.781416    19.08217   
min       1.000000     0.000000  1.886100e+06     0.000000     1.00000   
25%     250.750000     0.000000  2.815905e+06     0.000000    10.75000   
50%     500.500000     0.000000  4.092145e+06     0.500000    18.00000   
75%     750.250000     1.000000  6.545392e+06     1.000000    28.00000   
max    1000.000000     1.000000  6.759576e+07     2.000000   155.00000   

           1회 평균매출액    할인권 사용 횟수        총 할인 금액         고객등급         구매유형  \
count  1.000000e+03  1000.000000    1000.000000  1000.000000  1000.000000   
mean   3.521024e+05    16.027000  292371.670000     1.546000     2.656000   
std    3.124636e+05     8.341334  111937.501042     0.498129     1.046307   
min    2.708200e+04     1.000000    3750.000000     1.000000     1.000000   
25%    1.631242e+05     9.000000  261686.250000     1.000000     2.000000   
50%    2.582080e+05    17.000000  347500.000000     2.000000     2.000000   
75%    4.268310e+05    23.000000  365400.000000     2.000000     4.000000   
max    2.798500e+06    30.000000  400600.000000     2.000000     4.000000   

       ...      구매카테고리수         거주지역           성별       고객 나이대         거래기간  \
count  ...  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean   ...     5.217000     5.147000     0.189000     3.964000  3495.891000   
std    ...     2.224153     1.169084     0.391705     1.078827   965.966194   
min    ...     1.000000     1.000000     0.000000     2.000000   827.000000   
25%    ...     3.000000     4.000000     0.000000     3.000000  2871.000000   
50%    ...     5.000000     5.000000     0.000000     4.000000  3836.000000   
75%    ...     7.000000     6.000000     0.000000     5.000000  4207.250000   
max    ...     9.000000     7.000000     1.000000     7.000000  5334.000000   

            할인민감여부      Recency    Frequency     Monetary      평균 구매주기  
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000  
mean      0.400000     4.925000     2.289000     4.129000   266.880824  
std       0.490143     1.744253     1.669811     1.560383   254.077398  
min       0.000000     1.000000     1.000000     1.000000    13.980645  
25%       0.000000     4.000000     1.000000     3.000000   111.957671  
50%       0.000000     5.000000     2.000000     4.000000   191.469697  
75%       1.000000     7.000000     3.000000     6.000000   324.386218  
max       1.000000     7.000000     7.000000     7.000000  1956.000000  

[8 rows x 21 columns]

In [13]:
df.columns

Index(['고객ID', '이탈여부', '총매출액', '구매금액대', '방문빈도', '1회 평균매출액', '할인권 사용 횟수',
       '총 할인 금액', '고객등급', '구매유형', '클레임접수여부', '구매카테고리수', '거주지역', '성별', '고객 나이대',
       '거래기간', '할인민감여부', 'Recency', 'Frequency', 'Monetary', '평균 구매주기'],
      dtype='object')

In [16]:
under_500 = df[df["고객ID"] <= 500]
upper_500 = df[df["고객ID"] > 500]

print(under_500)
print(upper_500)

     고객ID  이탈여부     총매출액  구매금액대  방문빈도  1회 평균매출액  할인권 사용 횟수  총 할인 금액  고객등급  \
0       1     1  4963160      1    22    225598          1     5445     1   
1       2     1  2271520      0    38     59777         22   350995     1   
2       3     1  2484250      0     2   1242125          6   186045     1   
3       4     1  2778850      0     9    308761          1     5195     2   
4       5     1  4437610      1    10    443761          9   246350     2   
..    ...   ...      ...    ...   ...       ...        ...      ...   ...   
495   496     0  3738330      0    13    287564          5   132345     2   
496   497     0  1981390      0    14    141528         22   350550     1   
497   498     0  7583360      2    32    236980         12   303250     2   
498   499     0  4381950      1    19    230629         17   365145     2   
499   500     0  9875170      2    42    235123          8   260450     2   

     구매유형  ...  구매카테고리수  거주지역  성별  고객 나이대  거래기간  할인민감여부  Recency  Frequency

In [17]:
under_500.head()

고객ID  이탈여부     총매출액  구매금액대  방문빈도  1회 평균매출액  할인권 사용 횟수  총 할인 금액  고객등급  구매유형  \
0     1     1  4963160      1    22    225598          1     5445     1     3   
1     2     1  2271520      0    38     59777         22   350995     1     1   
2     3     1  2484250      0     2   1242125          6   186045     1     2   
3     4     1  2778850      0     9    308761          1     5195     2     4   
4     5     1  4437610      1    10    443761          9   246350     2     4   

   ...  구매카테고리수  거주지역  성별  고객 나이대  거래기간  할인민감여부  Recency  Frequency  Monetary  \
0  ...        7     6   1       6  3303       0        3          2         1   
1  ...        5     4   0       2  3129       0        5          3         4   
2  ...        4     6   0       3  3636       0        4          1         4   
3  ...        4     5   0       4  3637       0        7          4         6   
4  ...        6     6   0       4  3638       0        5          1         4   

       평균 구매주기  
0   149.136364  
1    81.342105  
2  1817.000000  
3   403.111111  
4   362.800000  

[5 rows x 21 columns]

In [18]:
upper_500.head()

고객ID  이탈여부      총매출액  구매금액대  방문빈도  1회 평균매출액  할인권 사용 횟수  총 할인 금액  고객등급  \
500   501     0   5746950      1    51    112685         20   368100     2   
501   502     0   2603520      0    19    137027         26   365150     1   
502   503     0   2815940      0    12    234662         20   347600     1   
503   504     0  10838570      2    33    328442          9   246795     2   
504   505     0   2227170      0    20    111359         29   374995     1   

     구매유형  ...  구매카테고리수  거주지역  성별  고객 나이대  거래기간  할인민감여부  Recency  Frequency  \
500     1  ...        8     4   1       4  4134       0        7          5   
501     4  ...        3     4   1       4  4135       0        4          1   
502     1  ...        3     4   0       3  4136       0        4          1   
503     4  ...        5     5   0       4  2569       1        1          3   
504     2  ...        3     5   1       5  3931       0        4          2   

     Monetary     평균 구매주기  
500         6   80.058824  
501         2  216.631579  
502         2  343.666667  
503         4   76.848485  
504         2  195.550000  

[5 rows x 21 columns]

In [19]:
df_join = under_500.append(upper_500)
print(df_join)

     고객ID  이탈여부      총매출액  구매금액대  방문빈도  1회 평균매출액  할인권 사용 횟수  총 할인 금액  고객등급  \
0       1     1   4963160      1    22    225598          1     5445     1   
1       2     1   2271520      0    38     59777         22   350995     1   
2       3     1   2484250      0     2   1242125          6   186045     1   
3       4     1   2778850      0     9    308761          1     5195     2   
4       5     1   4437610      1    10    443761          9   246350     2   
..    ...   ...       ...    ...   ...       ...        ...      ...   ...   
995   996     0  12731560      2    35    363759          3    44445     2   
996   997     0   3419010      0     6    569835          6   186545     1   
997   998     0   4612100      1    13    354777          8   260700     2   
998   999     0   5165360      1    28    184477         20   347700     1   
999  1000     0   4323050      1    16    270191         19   367045     2   

     구매유형  ...  구매카테고리수  거주지역  성별  고객 나이대  거래기간  할인민감여부  Recenc

In [36]:
y = df_join[["고객ID", "총매출액"]]

In [34]:
x = df_join[["고객ID", "방문빈도", "고객등급", "구매유형", "거주지역"]]

#대괄호가 두개인 것은 각각 인덱스와 리스트

In [37]:
x= pd.DataFrame(x)
y= pd.DataFrame(y)

In [38]:
x

고객ID  방문빈도  고객등급  구매유형  거주지역
0       1    22     1     3     6
1       2    38     1     1     4
2       3     2     1     2     6
3       4     9     2     4     5
4       5    10     2     4     6
..    ...   ...   ...   ...   ...
995   996    35     2     3     6
996   997     6     1     2     6
997   998    13     2     1     4
998   999    28     1     3     5
999  1000    16     2     4     5

[1000 rows x 5 columns]

In [39]:
y

고객ID      총매출액
0       1   4963160
1       2   2271520
2       3   2484250
3       4   2778850
4       5   4437610
..    ...       ...
995   996  12731560
996   997   3419010
997   998   4612100
998   999   5165360
999  1000   4323050

[1000 rows x 2 columns]

In [41]:
xy_merge = y.merge(x)
xy_merge

고객ID      총매출액  방문빈도  고객등급  구매유형  거주지역
0       1   4963160    22     1     3     6
1       2   2271520    38     1     1     4
2       3   2484250     2     1     2     6
3       4   2778850     9     2     4     5
4       5   4437610    10     2     4     6
..    ...       ...   ...   ...   ...   ...
995   996  12731560    35     2     3     6
996   997   3419010     6     1     2     6
997   998   4612100    13     2     1     4
998   999   5165360    28     1     3     5
999  1000   4323050    16     2     4     5

[1000 rows x 6 columns]