<a href="https://colab.research.google.com/github/kyungmo90/Ubion-Python/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%A7%88%EC%BC%80%ED%8C%85_%EB%B6%84%EC%84%9D_%EC%A0%84%EB%AC%B8%EA%B0%80_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

빅데이터 마케팅 분석 전문가 #2

박경모

2023.01.02.

In [1]:
a = 123
b = 'abc'
print(type(a), type(b))
print(a, b)

<class 'int'> <class 'str'>
123 abc


In [2]:
List = ["a", "b", "c", "d"]

In [3]:
List

['a', 'b', 'c', 'd']

In [4]:
Tuple = ("a","b","c","d")
Tuple

('a', 'b', 'c', 'd')

In [5]:
Dic = {"경기도" : "김포", "강원도" : "원주", "충청도" : "청주"}

In [6]:
Dic

{'경기도': '김포', '강원도': '원주', '충청도': '청주'}

In [7]:
score = 20
if score > 40 :
    print("vip")
else :
  print("member")

member


In [8]:
for i in [1,2,3,4,5] :
     print(i)

1
2
3
4
5


In [9]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [10]:
customer_count = 0
sum1 = 0

print("customer_count_sum")

while (sum1 < 20) :
    customer_count = customer_count + 1
    sum1 = sum1 + customer_count
    print(customer_count, sum1)

customer_count_sum
1 1
2 3
3 6
4 10
5 15
6 21


Numpy

In [16]:
from matplotlib import pyplot as pyplot
from pandas import DataFrame
import numpy as np
from pandas import *

In [17]:
data = {1,2,3,4,5,6}
arr1 = np.array(data)
arr1

array({1, 2, 3, 4, 5, 6}, dtype=object)

In [18]:
arr1.dtype

dtype('O')

In [20]:
arr1 = np.arange(start = 1, stop = 20, step = 2)
print(arr1)

[ 1  3  5  7  9 11 13 15 17 19]


In [23]:
arr1 = np.array([10,12,14,16,18])
arr2 = np.array([3,4,5,6,7])

print("----더하기----")
print(arr1+arr2)
print("----빼기----")
print(arr1-arr2)
print("----곱하기----")
print(arr1*arr2)
print("----나누기----")
print(arr1/arr2)

----더하기----
[13 16 19 22 25]
----빼기----
[ 7  8  9 10 11]
----곱하기----
[ 30  48  70  96 126]
----나누기----
[3.33333333 3.         2.8        2.66666667 2.57142857]


In [25]:
arr1[4] = 20
print(arr1)

[10 12 14 16 20]


In [27]:
arr1[1,3,4]

IndexError: ignored

In [30]:
arr3 = np.array([1,3,5,7,9,11])
arr3

array([ 1,  3,  5,  7,  9, 11])

In [32]:
arr3[1:5]

array([3, 5, 7, 9])

In [34]:
arr4 = np.arange(10)
arr4 = arr4.reshape(2,5,1)
arr4

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [35]:
arr5 = np.arange(20)
arr5 = arr5.reshape(-1,5)
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#pandas

In [36]:
import pandas as pd

In [37]:
series = pd.Series([1,2,3,4,5])
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [38]:
pd.DataFrame(series)

0
0  1
1  2
2  3
3  4
4  5

In [46]:
col_list = ["고객이름", "나이", "등급"]
val_list = [["박경모", 32, "silver"], ["원빈", 40, "gold"], ["옥동자", 45, "diamond"]]
pd.DataFrame(data = val_list, columns = col_list)

고객이름  나이       등급
0  박경모  32   silver
1   원빈  40     gold
2  옥동자  45  diamond

In [48]:
dict = {"고객이름" : ["박경모", "강동원", "옥동자"], "나이" : [34,40,45], "등급" : ["silver","diamond","gold"]}
pd.DataFrame(data = dict)

고객이름  나이       등급
0  박경모  34   silver
1  강동원  40  diamond
2  옥동자  45     gold

In [62]:
sales_data2 = {"화장품" : [300, 250, 150, 524, 211, 267, 192],
              "의류" : [170, 182, 193, 324, 487, 502, 810],
              "식품" : [220, 2310, 452, 520, 152, np.nan, np.nan],
              "전자제품" : [500, 345, 152, 540, 290, 125, 318]}
col_list = ["화장품", "의류", "식품", "전자제품"]
index_list = ["2017", "2018", "2019", "2020", "2021", "2022", "2023"]

df_sales2 = pd.DataFrame(data = sales_data2, columns = col_list, index = index_list)
df_sales2

화장품   의류      식품  전자제품
2017  300  170   220.0   500
2018  250  182  2310.0   345
2019  150  193   452.0   152
2020  524  324   520.0   540
2021  211  487   152.0   290
2022  267  502     NaN   125
2023  192  810     NaN   318

In [54]:
print(df_sales.mean())

화장품     287.0
의류      271.2
식품      730.8
전자제품    365.4
dtype: float64


In [55]:
print(df_sales.std())

화장품     143.398047
의류      135.711827
식품      896.097763
전자제품    158.306033
dtype: float64


In [56]:
df_sales.describe()

화장품          의류           식품        전자제품
count    5.000000    5.000000     5.000000    5.000000
mean   287.000000  271.200000   730.800000  365.400000
std    143.398047  135.711827   896.097763  158.306033
min    150.000000  170.000000   152.000000  152.000000
25%    211.000000  182.000000   220.000000  290.000000
50%    250.000000  193.000000   452.000000  345.000000
75%    300.000000  324.000000   520.000000  500.000000
max    524.000000  487.000000  2310.000000  540.000000

In [64]:
df_sales2.loc["2022"]

화장품     267.0
의류      502.0
식품        NaN
전자제품    125.0
Name: 2022, dtype: float64

In [66]:
df_sales2["식품"]["2022":"2023"]

2022   NaN
2023   NaN
Name: 식품, dtype: float64

In [67]:
df_sales2.loc["2022","식품"]

nan

In [73]:
df_sales2.iloc[2:4,0]

2019    150
2020    524
Name: 화장품, dtype: int64

In [74]:
df_sales2.columns

Index(['화장품', '의류', '식품', '전자제품'], dtype='object')

In [76]:
df_sales2.isnull().sum()

화장품     0
의류      0
식품      2
전자제품    0
dtype: int64

In [77]:
df_sales2_row = df_sales2.dropna(axis=0)
df_sales2_row

화장품   의류      식품  전자제품
2017  300  170   220.0   500
2018  250  182  2310.0   345
2019  150  193   452.0   152
2020  524  324   520.0   540
2021  211  487   152.0   290

In [78]:
df_sales2_col = df_sales2.dropna(axis=1)
df_sales2_col

화장품   의류  전자제품
2017  300  170   500
2018  250  182   345
2019  150  193   152
2020  524  324   540
2021  211  487   290
2022  267  502   125
2023  192  810   318

In [79]:
df_sales2_zero = df_sales2.fillna(0)
df_sales2_zero

화장품   의류      식품  전자제품
2017  300  170   220.0   500
2018  250  182  2310.0   345
2019  150  193   452.0   152
2020  524  324   520.0   540
2021  211  487   152.0   290
2022  267  502     0.0   125
2023  192  810     0.0   318

In [84]:
df_sales2_mean = df_sales2.fillna(df_sales2["식품"].mean())
df_sales2_mean

화장품   의류      식품  전자제품
2017  300  170   220.0   500
2018  250  182  2310.0   345
2019  150  193   452.0   152
2020  524  324   520.0   540
2021  211  487   152.0   290
2022  267  502   730.8   125
2023  192  810   730.8   318